export enum MovementType {
  RECEIVE = 'RECEIVE',
  ISSUE = 'ISSUE',
  TRANSFER_OUT = 'TRANSFER_OUT',
  TRANSFER_IN = 'TRANSFER_IN',
  ADJUSTMENT = 'ADJUSTMENT',
  RESERVATION = 'RESERVATION',
  RELEASE = 'RELEASE',
  RETURN = 'RETURN',
  WRITE_OFF = 'WRITE_OFF',
  COUNT_CORRECTION = 'COUNT_CORRECTION'
}
