export enum NaturalAccount {
  CASH = 'CASH',
  BANK = 'BANK',
  RECEIVABLE = 'RECEIVABLE',
  PAYABLE = 'PAYABLE',
  INVENTORY = 'INVENTORY',
  FIXED_ASSET = 'FIXED_ASSET',
  ACCUMULATED_DEPRECIATION = 'ACCUMULATED_DEPRECIATION',
  REVENUE_OPERATING = 'REVENUE_OPERATING',
  EXPENSE_OPERATING = 'EXPENSE_OPERATING',
  TAX_PAYABLE = 'TAX_PAYABLE',
  TAX_RECEIVABLE = 'TAX_RECEIVABLE',
  EQUITY_CAPITAL = 'EQUITY_CAPITAL',
  EQUITY_RETAINED_EARNINGS = 'EQUITY_RETAINED_EARNINGS'
}
