export enum PresentationGroup {
  CURRENT_ASSETS = 'CURRENT_ASSETS',
  NON_CURRENT_ASSETS = 'NON_CURRENT_ASSETS',
  CURRENT_LIABILITIES = 'CURRENT_LIABILITIES',
  NON_CURRENT_LIABILITIES = 'NON_CURRENT_LIABILITIES',
  OPERATING_REVENUE = 'OPERATING_REVENUE',
  NON_OPERATING_REVENUE = 'NON_OPERATING_REVENUE',
  COST_OF_GOODS_SOLD = 'COST_OF_GOODS_SOLD',
  OPERATING_EXPENSES = 'OPERATING_EXPENSES',
  SHAREHOLDERS_EQUITY = 'SHAREHOLDERS_EQUITY'
}
